### ISSUE TITLE
计算原理和精度问题

### ISSUE THREAD

**Issue by LunaLuan9555** [lhprojects/erfz#1]
你好！我想知道这个erfz是基于哪种数值计算理论实现的，源码看起来不像泰勒展开，而我没太弄明白它的具体细节，是增量法吗？
另外我在处理一些虚部很大的数值的erfz的计算，比较关心它在函数值虚部非常大的情况下的精确程度。（忘记在哪里看到的，泰勒展开的收敛性在某些情况下不是很理想）

**Comment by lhprojects** [comment]
@LunaLuan9555 你好！实现请见本子的论文 https://granite.phys.s.u-tokyo.ac.jp/svn/LCGT/trunk/sensitivity/Matlab/official/@double/erfz.pdf 。没有使用直接泰勒展开。你说到的虚数部分很大？我的理解是erfz按照exp(Im(z)^2 - Re(z)^2)的速度发散的，所以Im(z)也不能太大吧。我刚刚更新了一下，尽量在所有情况下有比较小的round error，精度见 https://github.com/lhprojects/erfz/blob/master/precision.txt 。如果你还需要这个函数，你最好自己试一试，和 https://www.wolframalpha.com/input/?i=erf%281+%2B+1*I%29 的结果对比一下，看看能不能满足你的需求。
